### ISSUE TITLE
code:Unauthorized  message:Access to requested resource is denied.

### ISSUE THREAD

**Issue by wanghuoling** [ionafan2/selling-partner-api-php-sandbox#1]
@ionafan2 ,I got this message:
GET https://sellingpartnerapi-na.amazon.com/orders/v0/orders?MarketplaceIds=ATVPDKIKX0DER&CreatedAfter=2020-12-03` resulted in a `403 Forbidden` response: { "errors": [ { "message": "Access to requested resource is denied.", "code": "Unauthorized", "det (truncated...).
following your readme.md document's step.I replaced .env file's  parameters:SP_API_APP_CLIENT_ID,SP_API_APP_CLIENT_SECRET,AWS_USER_KEY,AWS_USER_SECRET,AWS_ROLE_ARM and REFRESH_TOKEN. REFRESH_TOKEN get from my "Self Authorization". But the error same too.My selling partner application is "draft"  status.

**Comment by wanghuoling** [comment]
and then,my selling partner account and my aws account is difference.they are two difference email,Does this matter?

**Comment by ionafan2** [comment]
> and then,my selling partner account and my aws account is difference.they are two difference email,Does this matter?

I have the same account. So this could be a problem. But I think it shouldn’t matter, because our AWS Users's Role Arm in your Application. Double-check your `.env` file.

**Comment by wanghuoling** [comment]
@ionafan2   my problem has solved.thanks a lot.

**Comment by zachary** [comment]
> @ionafan2 my problem has solved.thanks a lot.

How to solve this issue?
thanks a lot.

**Comment by ionafan2** [comment]
> > @ionafan2 my problem has solved.thanks a lot.
> 
> How to solve this issue?
> thanks a lot.

@zachary ask @wanghuoling about it :)
