### ISSUE TITLE
Q: Request signing of /auth/o2/token

### ISSUE THREAD

**Issue by gasper-vrhovsek** [ionafan2/selling-partner-api-php-sandbox#2]
Hello!

It's awesome to see this project demonstrate how LWA & SP-API should be used. I have two questions: 

1. Do requests to /auth/o2/token have to be signed? Because while doing self authorization I managed to get the refresh and access tokens via curl commant to /auth/o2/token.

Example of the curl command:
```
curl --location --request POST 'https://api.amazon.com/auth/o2/token' --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'refresh_token=Atzr|IXXXX.....' --data-urlencode 'client_id=amzn1.application-oa2-client.XXXXXXX' --data-urlencode 'client_secret=f5XXXXXX...' --data-urlencode 'code_verifier=a51c5c8a-2d3f-43ad-9631-6f81fb017a0' --data-urlencode 'grant_type=refresh_token'
```

2. Did you manage to exchange an access code for the refresh and access tokens? I saw you wrote the function for it but it isn't used in the project

Thanks for your answer,
Gasper

**Comment by gasper-vrhovsek** [comment]
@ionafan2 i have just successfully tested exchanging the spapi_oauth_code for access and refresh LWA tokens. I'll leave this issue open if you maybe know the answer to the original question (signing of the request).

**Comment by ionafan2** [comment]
@gasper-vrhovsek  I do sign every request as you can see in the [AbstractClient](https://github.com/ionafan2/selling-partner-api-php-sandbox/blob/main/src/Client/AbstractClient.php). So it may accept calls to `/auth/o2/token` without signing. I never tried. 
Anyway, today it’s working in both ways **with** and **without** signing. But who knows if it’s going to work like that latter. They might turn on signature check down the road. SP API is a new product and I guess they will roll out changes soon.

**Comment by gasper-vrhovsek** [comment]
@ionafan2 Thanks for your reply. Yes, I noticed  you're signing all requests. I asked, because i couldn't find anything regarding `/auth/o2/token` request signing in amazons documentation. But yes, i agree, better to sign than not to.
