### ISSUE TITLE
Unauthorized Issue

### ISSUE THREAD

**Issue by kingsun-he** [ionafan2/selling-partner-api-php-sandbox#3]
It make me depressed. Though I have fill every value in .env file, when I run index.php. The response is 403.

`Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://sellingpartnerapi-na.amazon.com/orders/v0/orders?MarketplaceIds=ATVPDKIKX0DER&CreatedAfter=2021-01-21` resulted in a `403 Forbidden` response: { "errors": [ { "message": "Access to requested resource is denied.", "code": "Unauthorized", "det (truncated...)

**Comment by ionafan2** [comment]
Are you 101% sure you completed required steps before run?
And did the step below?
Follow [Self Authorization](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#self-authorization) and receive `refresh_token`

**Comment by kingsun-he** [comment]
> Are you 101% sure you completed required steps before run?
> And did the step below?
> Follow [Self Authorization](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#self-authorization) and receive `refresh_token`
