### ISSUE TITLE
Unauthorized Issue

### ISSUE THREAD

**Issue by kingsun-he** [ionafan2/selling-partner-api-php-sandbox#4]
It make me depressed. Though I have fill every value in .env file, when I run index.php. The response is 403.

Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: GET https://sellingpartnerapi-na.amazon.com/orders/v0/orders?MarketplaceIds=ATVPDKIKX0DER&CreatedAfter=2021-01-21` resulted in a 403 Forbidden response: { "errors": [ { "message": "Access to requested resource is denied.", "code": "Unauthorized", "det (truncated...)

@ionafan2
 
Owner
ionafan2 commented 2 hours ago
Are you 101% sure you completed required steps before run?
And did the step below?
Follow Self Authorization and receive refresh_token

Yes. I did.
My info like this:

SP_API_APP_CLIENT_ID=amzn1.application-xxxxxxxxx5c5b54
SP_API_APP_CLIENT_SECRET=50e754dfb2xxxxxxxxd7d2cedad1b
AWS_USER_KEY=AKIxxxxxxxxxMWXUV
AWS_USER_SECRET=lYrxxxxxxxxxTuzj
AWS_ROLE_ARM=arn:aws:iam::xxxxxxxxxxxxx:role/SellerPartnerAPIRole
AWS_REGION=us-east-1
AWS_STS_VERSION=2011-06-15
AUTH_API_HOST=https://api.amazon.com
BASE_API_HOST=https://sellingpartnerapi-na.amazon.com
MARKETPLACE_ID=ATVPDKIKX0DER
REFRESH_TOKEN=Atzr|IwEBILt6_L8opcxxxxxxxxxuHnWy8

Any idea?

**Comment by kingsun-he** [comment]
Last year I have registerd as a MWS developer. Is there any difference between MWS developer and SP-API developer? Do I need to register another new developer?

**Comment by kingsun-he** [comment]
HaHa, It works. 

I change 2 value of .env
AWS_REGION=eu-west-1
BASE_API_HOST=https://sellingpartnerapi-eu.amazon.com

Orginally,
They are "us-east-1" and "https://sellingpartnerapi-na.amazon.com".

I didn't understand it yet.  But anyway, it works. I will study it further more.

Thanks a lot, ionafan2. You help me a lot really.
@ionafan2

**Comment by ionafan2** [comment]
@kingsun-he It depends on where you registered your application.
And don’t forget about `MARKETPLACE_ID=` it's different for  `sellingpartnerapi-eu.amazon.com`
Take a look at [Selling Partner API endpoints](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#selling-partner-api-endpoints) and [marketplaceId values](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#marketplaceid-values)

**Comment by kingsun-he** [comment]
Hi ionafan2, 
Can you try to apply getSolicitationActionsForOrder operation in solicitations-api?  I got a error “Access to requested resource is denied”

`Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://sandbox.sellingpartnerapi-eu.amazon.com/solicitations/v1/orders/123-1234567-1234567?marketplaceIds=ATVPDKIKX0DER` resulted in a `403 Forbidden` response:
{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "det (truncated...)`

======================
Here is my code:

$response = $this->send(
            'GET',
            '/solicitations/v1/orders/' . $amazonOrderId,
            [
                'marketplaceIds' => implode(',', $marketplaceIds),
            ],
            ["x-amz-access-token" => $this->accessToken]
        );

        if (0 === count((array)$response['payload'])) {
            return null;
        }
====

Same as your OrderClient class. I wonder if some SP-API doesn't work. @ionafan2

**Comment by kingsun-he** [comment]
Hi ionafan2, 

It seems that it the bug of sandbox environment. I have test this api by a real amazon order. It is completely OK. Thanks for your help. I will close this issue.
