### ISSUE TITLE
How to use sandbox Call?

### ISSUE THREAD

**Issue by kingsun-he** [ionafan2/selling-partner-api-php-sandbox#5]
I changed the endpoint to "https://sandbox.sellingpartnerapi-eu.amazon.com". But I get the error response:

`"errors": [
    {
      "message": "We encountered an internal error. Please try again.",
     "code": "InternalFail (truncated...)`

Do you try to use the sandbox function？@ionafan2

**Comment by ionafan2** [comment]
@kingsun-he I just tried and it works just fine.
Read about [Step 1. Check the JSON file for request parameters](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-1-check-the-json-file-for-request-parameters).
For example for `/orders/v0/orders` you need to specify `CreatedAfter`  if you put there `TEST_CASE_200 ` sandbox will return a proper result. 
see [x-amazon-spds-sandbox-behaviors](https://github.com/amzn/selling-partner-api-models/blob/main/models/orders-api-model/ordersV0.json#L156) for ordersV0.json
